//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Windows.Azure.BizTalkService.ClientTools.TpmMigration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Windows.Azure.BizTalkService.ClientTools.TpmMigration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAD Instance : .
        /// </summary>
        public static string AADInstanceLabel {
            get {
                return ResourceManager.GetString("AADInstanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered ACS details are incorrect.
        /// </summary>
        public static string AcsDetailsValidatioError {
            get {
                return ResourceManager.GetString("AcsDetailsValidatioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS Namespace :.
        /// </summary>
        public static string AcsNamespaceLabel {
            get {
                return ResourceManager.GetString("AcsNamespaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS Namespace cannot be empty.
        /// </summary>
        public static string AcsNamespaceValidationError {
            get {
                return ResourceManager.GetString("AcsNamespaceValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} agreements were successfully migrated to IA..
        /// </summary>
        public static string AgreementExportSummaryFormat {
            get {
                return ResourceManager.GetString("AgreementExportSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Agreement(s) Json.
        /// </summary>
        public static string AgreementImportPageTitle {
            get {
                return ResourceManager.GetString("AgreementImportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Agreements Json.
        /// </summary>
        public static string AgreementImportStepDescriptionText {
            get {
                return ResourceManager.GetString("AgreementImportStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} agreements were successfully exported to Json..
        /// </summary>
        public static string AgreementImportSummaryFormat {
            get {
                return ResourceManager.GetString("AgreementImportSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Name.
        /// </summary>
        public static string AgreementNameColumnHeader {
            get {
                return ResourceManager.GetString("AgreementNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Agreements.
        /// </summary>
        public static string AgreementSelectionPageTitle {
            get {
                return ResourceManager.GetString("AgreementSelectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Agreements.
        /// </summary>
        public static string AgreementSelectionStepDescriptionText {
            get {
                return ResourceManager.GetString("AgreementSelectionStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Logic/integrationAccounts/agreements.
        /// </summary>
        public static string AgreementType {
            get {
                return ResourceManager.GetString("AgreementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Name.
        /// </summary>
        public static string ArtifactNameColumnHeader {
            get {
                return ResourceManager.GetString("ArtifactNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Type.
        /// </summary>
        public static string ArtifactTypeColumnHeader {
            get {
                return ResourceManager.GetString("ArtifactTypeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        public static string AssemblynameColumnHeader {
            get {
                return ResourceManager.GetString("AssemblynameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Credentials.
        /// </summary>
        public static string AuthenticationSectionTitle {
            get {
                return ResourceManager.GetString("AuthenticationSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide BizTalk Management Database Connection Details.
        /// </summary>
        public static string BizTalkManagementDbDetailsPageTitle {
            get {
                return ResourceManager.GetString("BizTalkManagementDbDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} certificates were successfully migrated to IA..
        /// </summary>
        public static string CertificateExportSummaryFormat {
            get {
                return ResourceManager.GetString("CertificateExportSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} certificates were successfully exported to Json..
        /// </summary>
        public static string CertificateImportSummaryFormat {
            get {
                return ResourceManager.GetString("CertificateImportSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID : .
        /// </summary>
        public static string ClientIdLabel {
            get {
                return ResourceManager.GetString("ClientIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Secret : .
        /// </summary>
        public static string ClientSecretLabel {
            get {
                return ResourceManager.GetString("ClientSecretLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseNavigationButtonLabel {
            get {
                return ResourceManager.GetString("CloseNavigationButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database :.
        /// </summary>
        public static string DatabaseNameLabel {
            get {
                return ResourceManager.GetString("DatabaseNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name cannot be empty.
        /// </summary>
        public static string DatabaseNameValidationError {
            get {
                return ResourceManager.GetString("DatabaseNameValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        public static string DbPasswordLabel {
            get {
                return ResourceManager.GetString("DbPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name :.
        /// </summary>
        public static string DbUserNameLabel {
            get {
                return ResourceManager.GetString("DbUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Url :.
        /// </summary>
        public static string DeploymentUrlLabel {
            get {
                return ResourceManager.GetString("DeploymentUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Url cannot be empty.
        /// </summary>
        public static string DeploymentUrlValidationError {
            get {
                return ResourceManager.GetString("DeploymentUrlValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA (Destination).
        /// </summary>
        public static string DestinationDetailsStepDescriptionText {
            get {
                return ResourceManager.GetString("DestinationDetailsStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to Use different account to access Certificates from Remote Biztalk Server?.
        /// </summary>
        public static string DifferentAccountSectionTitle {
            get {
                return ResourceManager.GetString("DifferentAccountSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadMe\MigrationToolReadme.docx.
        /// </summary>
        public static string DocumentationLink {
            get {
                return ResourceManager.GetString("DocumentationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured in fetching ACS token.
        /// </summary>
        public static string ErrorGettingACSToken {
            get {
                return ResourceManager.GetString("ErrorGettingACSToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while reading TPM configuration from BizTalk DB..
        /// </summary>
        public static string ErrorReadingTpmConfig {
            get {
                return ResourceManager.GetString("ErrorReadingTpmConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors were encountered by the TPM migration tool..
        /// </summary>
        public static string ErrorSummaryMessage {
            get {
                return ResourceManager.GetString("ErrorSummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating Artifacts To Integration Account.
        /// </summary>
        public static string ExportArtifactsStatusPageTitle {
            get {
                return ResourceManager.GetString("ExportArtifactsStatusPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Status.
        /// </summary>
        public static string ExportArtifactsStatusStepDescription {
            get {
                return ResourceManager.GetString("ExportArtifactsStatusStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating {0} to Integration Account.
        /// </summary>
        public static string ExportingArtifactsProgressBarText {
            get {
                return ResourceManager.GetString("ExportingArtifactsProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} migrated successfully.
        /// </summary>
        public static string ExportSuccessMessageText {
            get {
                return ResourceManager.GetString("ExportSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Artifacts To Migrate To Integration Account.
        /// </summary>
        public static string ExportToIAPageTitle {
            get {
                return ResourceManager.GetString("ExportToIAPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate To IA.
        /// </summary>
        public static string ExportToIntegrationAccountStepDescription {
            get {
                return ResourceManager.GetString("ExportToIntegrationAccountStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Prepare Artifact(s) Json.
        /// </summary>
        public static string ExportToJsonSummaryTitle {
            get {
                return ResourceManager.GetString("ExportToJsonSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Json.
        /// </summary>
        public static string ExportToJsonText {
            get {
                return ResourceManager.GetString("ExportToJsonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} can be found at {1}{2}.
        /// </summary>
        public static string FileLocationText {
            get {
                return ResourceManager.GetString("FileLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration.log.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Partner.
        /// </summary>
        public static string GuestPartnerColumnHeader {
            get {
                return ResourceManager.GetString("GuestPartnerColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted Partner.
        /// </summary>
        public static string HostedPartnerColumnHeader {
            get {
                return ResourceManager.GetString("HostedPartnerColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted Partner.
        /// </summary>
        public static string HostedPartnerSelectionColumnHeader {
            get {
                return ResourceManager.GetString("HostedPartnerSelectionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing agreements with data from Biztalk Database Server.
        /// </summary>
        public static string ImportingAgreementsProgressBarText {
            get {
                return ResourceManager.GetString("ImportingAgreementsProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing partners with data from Biztalk Database Server.
        /// </summary>
        public static string ImportingPartnersProgressBarText {
            get {
                return ResourceManager.GetString("ImportingPartnersProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Schemas with data from Biztalk Database Server.
        /// </summary>
        public static string ImportingSchemasProgressBarText {
            get {
                return ResourceManager.GetString("ImportingSchemasProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Json prepared successfully.
        /// </summary>
        public static string ImportSuccessMessageText {
            get {
                return ResourceManager.GetString("ImportSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Account Name.
        /// </summary>
        public static string IntegrationAccountNameLabel {
            get {
                return ResourceManager.GetString("IntegrationAccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Logic Apps Platform Details.
        /// </summary>
        public static string IntegrationServiceDetailsPageTitle {
            get {
                return ResourceManager.GetString("IntegrationServiceDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Account Details.
        /// </summary>
        public static string InterationAccountDetailsLabel {
            get {
                return ResourceManager.GetString("InterationAccountDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Key :.
        /// </summary>
        public static string IssuerKeyLabel {
            get {
                return ResourceManager.GetString("IssuerKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Key cannot be empty.
        /// </summary>
        public static string IssuerKeyValidationError {
            get {
                return ResourceManager.GetString("IssuerKeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Name :.
        /// </summary>
        public static string IssuerNameLabel {
            get {
                return ResourceManager.GetString("IssuerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Name cannot be empty.
        /// </summary>
        public static string IssuerNameValidationError {
            get {
                return ResourceManager.GetString("IssuerNameValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files\Agreements\{0}{1}.
        /// </summary>
        public static string JsonAgreementFilesLocalPath {
            get {
                return ResourceManager.GetString("JsonAgreementFilesLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files\Certificates\{0}{1}.
        /// </summary>
        public static string JsonCertificateFilesLocalPath {
            get {
                return ResourceManager.GetString("JsonCertificateFilesLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files\KeyVault\{0}{1}.
        /// </summary>
        public static string JsonKeyVaultFilesLocalPath {
            get {
                return ResourceManager.GetString("JsonKeyVaultFilesLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Logic/integrationAccounts/agreements.
        /// </summary>
        public static string JsonPartnerAgreementType {
            get {
                return ResourceManager.GetString("JsonPartnerAgreementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files\Partners\{0}{1}.
        /// </summary>
        public static string JsonPartnerFilesLocalPath {
            get {
                return ResourceManager.GetString("JsonPartnerFilesLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /subscriptions/{0}/resourceGroups/{1}/providers/Microsoft.Logic/integrationAccounts/{2}/partners/{3}.
        /// </summary>
        public static string JsonPartnerID {
            get {
                return ResourceManager.GetString("JsonPartnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Logic/integrationAccounts/partners.
        /// </summary>
        public static string JsonPartnerType {
            get {
                return ResourceManager.GetString("JsonPartnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B.
        /// </summary>
        public static string JsonPartnerTypeB2B {
            get {
                return ResourceManager.GetString("JsonPartnerTypeB2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files\Schemas\.
        /// </summary>
        public static string JsonSchemaFilesLocalPath {
            get {
                return ResourceManager.GetString("JsonSchemaFilesLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files\Schemas\{0}{1}.
        /// </summary>
        public static string JsonSchemasFilesLocalPath {
            get {
                return ResourceManager.GetString("JsonSchemasFilesLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Vault Name.
        /// </summary>
        public static string KeyVaultNameLabel {
            get {
                return ResourceManager.GetString("KeyVaultNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logfile.
        /// </summary>
        public static string LogFileLabel {
            get {
                return ResourceManager.GetString("LogFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files\LogFile\{0}.
        /// </summary>
        public static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files\{0}\.
        /// </summary>
        public static string MetaDataContextPath {
            get {
                return ResourceManager.GetString("MetaDataContextPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Migrate Artifacts to Integration Account.
        /// </summary>
        public static string MigrateToIASumaryTitle {
            get {
                return ResourceManager.GetString("MigrateToIASumaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating.
        /// </summary>
        public static string MigrateToIaText {
            get {
                return ResourceManager.GetString("MigrateToIaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Errors were encountered while {0} of one or more agreement(s)..
        /// </summary>
        public static string MigrationErrorSummaryMessageForAgreement {
            get {
                return ResourceManager.GetString("MigrationErrorSummaryMessageForAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Errors were encountered while {0} of one or more certificate(s)..
        /// </summary>
        public static string MigrationErrorSummaryMessageForCert {
            get {
                return ResourceManager.GetString("MigrationErrorSummaryMessageForCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Errors were encountered while {0} of one or more partner(s)..
        /// </summary>
        public static string MigrationErrorSummaryMessageForPartner {
            get {
                return ResourceManager.GetString("MigrationErrorSummaryMessageForPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Errors were encountered while {0} of one or more schema(s)..
        /// </summary>
        public static string MigrationErrorSummaryMessageForSchema {
            get {
                return ResourceManager.GetString("MigrationErrorSummaryMessageForSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing and/or encryption settings have not been migrated for this artifact.
        /// </summary>
        public static string MigrationPartialMessageText {
            get {
                return ResourceManager.GetString("MigrationPartialMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MigrationStatusColumnHeader {
            get {
                return ResourceManager.GetString("MigrationStatusColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextNavigationButtonLabel {
            get {
                return ResourceManager.GetString("NextNavigationButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No partners/agreements were selected for migration..
        /// </summary>
        public static string NoAgreementsOrPartnersSelectedErrorMessage {
            get {
                return ResourceManager.GetString("NoAgreementsOrPartnersSelectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the partners require any certificate. No Certificates were migrated. .
        /// </summary>
        public static string NoCertificatesRequiredSummary {
            get {
                return ResourceManager.GetString("NoCertificatesRequiredSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} {2} already exists in IA. Since the Overwrite was disabled, they were not overwritten..
        /// </summary>
        public static string NoOverWriteArtfact {
            get {
                return ResourceManager.GetString("NoOverWriteArtfact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since no partner was selected, no certificates were migrated..
        /// </summary>
        public static string NoPartnerSelectedSoNoCertificateMigrated {
            get {
                return ResourceManager.GetString("NoPartnerSelectedSoNoCertificateMigrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} {2} already exists in IA. Since Overwrite was enabled, they were overwritten in IA..
        /// </summary>
        public static string OverWriteArtifact {
            get {
                return ResourceManager.GetString("OverWriteArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} partners were successfully migrated to IA..
        /// </summary>
        public static string PartnerExportSummaryFormat {
            get {
                return ResourceManager.GetString("PartnerExportSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Partner(s) Json.
        /// </summary>
        public static string PartnerImportPageTitle {
            get {
                return ResourceManager.GetString("PartnerImportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Partners Json.
        /// </summary>
        public static string PartnerImportStepDescriptionText {
            get {
                return ResourceManager.GetString("PartnerImportStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} partners were successfully exported to Json..
        /// </summary>
        public static string PartnerImportSummaryFormat {
            get {
                return ResourceManager.GetString("PartnerImportSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Name.
        /// </summary>
        public static string PartnerNameColumnHeader {
            get {
                return ResourceManager.GetString("PartnerNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Partners.
        /// </summary>
        public static string PartnerSelectionPageTitle {
            get {
                return ResourceManager.GetString("PartnerSelectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Partners.
        /// </summary>
        public static string PartnerSelectionStepDescriptionText {
            get {
                return ResourceManager.GetString("PartnerSelectionStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string PasswordValidationError {
            get {
                return ResourceManager.GetString("PasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PreviousNavigationButtonLabel {
            get {
                return ResourceManager.GetString("PreviousNavigationButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Count.
        /// </summary>
        public static string ProfileCountColumnHeader {
            get {
                return ResourceManager.GetString("ProfileCountColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string ProtocolColumnHeader {
            get {
                return ResourceManager.GetString("ProtocolColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading agreements from BizTalk Server.
        /// </summary>
        public static string ReadingAgreementsProgressBarText {
            get {
                return ResourceManager.GetString("ReadingAgreementsProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading partners from BizTalk Server.
        /// </summary>
        public static string ReadingPartnersProgressBarText {
            get {
                return ResourceManager.GetString("ReadingPartnersProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading schemas from BizTalk Server.
        /// </summary>
        public static string ReadingSchemasProgressBarText {
            get {
                return ResourceManager.GetString("ReadingSchemasProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain :.
        /// </summary>
        public static string RemoteDomainNameLabel {
            get {
                return ResourceManager.GetString("RemoteDomainNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        public static string RemotePasswordLabel {
            get {
                return ResourceManager.GetString("RemotePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztalk Server Name : .
        /// </summary>
        public static string RemoteServerNameLabel {
            get {
                return ResourceManager.GetString("RemoteServerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Biztalk Server Details.
        /// </summary>
        public static string RemoteServerSectionTitle {
            get {
                return ResourceManager.GetString("RemoteServerSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username : .
        /// </summary>
        public static string RemoteUserNameLabel {
            get {
                return ResourceManager.GetString("RemoteUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty.
        /// </summary>
        public static string RemoteValidationError {
            get {
                return ResourceManager.GetString("RemoteValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Group Name.
        /// </summary>
        public static string ResourceGroupLabel {
            get {
                return ResourceManager.GetString("ResourceGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource : .
        /// </summary>
        public static string ResourceLabel {
            get {
                return ResourceManager.GetString("ResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} schemas were successfully migrated to IA..
        /// </summary>
        public static string SchemaExportSummaryFormat {
            get {
                return ResourceManager.GetString("SchemaExportSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Schema(s) Definitions.
        /// </summary>
        public static string SchemaImportPageTitle {
            get {
                return ResourceManager.GetString("SchemaImportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Schemas Definitions.
        /// </summary>
        public static string SchemaImportStepDescriptionText {
            get {
                return ResourceManager.GetString("SchemaImportStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} schemas were successfully prepared.
        /// </summary>
        public static string SchemaImportSummaryFormat {
            get {
                return ResourceManager.GetString("SchemaImportSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Name.
        /// </summary>
        public static string SchemaNameColumnHeader {
            get {
                return ResourceManager.GetString("SchemaNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Schemas.
        /// </summary>
        public static string SchemaSelectionPageTitle {
            get {
                return ResourceManager.GetString("SchemaSelectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Schemas.
        /// </summary>
        public static string SchemaSelectionStepDescriptionText {
            get {
                return ResourceManager.GetString("SchemaSelectionStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server :.
        /// </summary>
        public static string ServerNameLabel {
            get {
                return ResourceManager.GetString("ServerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name cannot be empty.
        /// </summary>
        public static string ServerNameValidationError {
            get {
                return ResourceManager.GetString("ServerNameValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Server (Source).
        /// </summary>
        public static string SourceDetailsStepDescriptionText {
            get {
                return ResourceManager.GetString("SourceDetailsStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Authentication.
        /// </summary>
        public static string SqlAuthenticationLabel {
            get {
                return ResourceManager.GetString("SqlAuthenticationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered SQL details are incorrect.
        /// </summary>
        public static string SqlConnectionValidationError {
            get {
                return ResourceManager.GetString("SqlConnectionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Name.
        /// </summary>
        public static string SubscriptionNameLabel {
            get {
                return ResourceManager.GetString("SubscriptionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryPageTitle {
            get {
                return ResourceManager.GetString("SummaryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryStepDescriptionText {
            get {
                return ResourceManager.GetString("SummaryStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTSMigrationTool@microsoft.com.
        /// </summary>
        public static string SupportDL {
            get {
                return ResourceManager.GetString("SupportDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk To Logic Apps Migration Tool.
        /// </summary>
        public static string TpmMigrationToolTitle {
            get {
                return ResourceManager.GetString("TpmMigrationToolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error was encountered..
        /// </summary>
        public static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} {2} Json migration failed. They cannot be migrated to IA..
        /// </summary>
        public static string UnSuccesfullExport {
            get {
                return ResourceManager.GetString("UnSuccesfullExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} {2} Json creation failed. They cannot be migrated to IA..
        /// </summary>
        public static string UnSuccesfullImport {
            get {
                return ResourceManager.GetString("UnSuccesfullImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id cannot be empty.
        /// </summary>
        public static string UserIdValidationError {
            get {
                return ResourceManager.GetString("UserIdValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Missing, Field cannot be empty..
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionColumnHeader {
            get {
                return ResourceManager.GetString("VersionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before You Begin.
        /// </summary>
        public static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeStepDescriptionText {
            get {
                return ResourceManager.GetString("WelcomeStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPM wizard guides you in migrating X12, EDIFACT and AS2 agreements from BizTalk Server to Logic Apps.
        ///
        ///In the wizard you will specify access information of both BizTalk Server and Azure Logic Apps. You will also have the option to choose the Partners and Agreements to be migrated. 
        ///
        ///After the migration is complete, you can login to the Azure management portal and verify the migrated partner and agreement settings..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Authentication.
        /// </summary>
        public static string WindowsAuthenticationLabel {
            get {
                return ResourceManager.GetString("WindowsAuthenticationLabel", resourceCulture);
            }
        }
    }
}
